### ISSUE TITLE
Scripture (Book) Not Saved 

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Saivite-Bible#83]
On the "Scripture level editing and notes" on the very bottom of the screen (should apply to the whole "book")  When you hit "Submit" we get a dialogue box that shows html and some error relating to php, and they are not registered in the base. The you go away for the and come back, they are blank

**Comment by subhakanta1979** [comment]
Yes, this is a known issue , we are working on it, should be Fixed by tomorrow.

**Comment by subhakanta1979** [comment]
This is pending from our end as we were caught up with issues in the chapters interface. We will finish it ASAP as soon as the New Server is up and running.

**Comment by subhakanta1979** [comment]
This is Fixed, we are able to save at Verse Level, Chapter Level and at Document Level.

**Comment by subhakanta1979** [comment]
![image](https://user-images.githubusercontent.com/43493826/65087240-77eea980-d9d2-11e9-8bf0-928d927e1b50.png)
This is Fixed, we are able to save at Verse Level, Chapter Level and at Document Level.
Added a New Field to the DB because reviewer notes field is already being used at the Verse Level.

**Comment by Arumugaswami** [comment]
You were going to publish your changes to the service [without charging us] but we still don't see what you say is fixed:
1. I can enter comments in the reviewers notes, verse bhasyas, verse translators' notes
2. save  and publish-> and then manually select the next verse from the top menu and all the comments appear in all the verses.
3. The buttons previous and next do not work.
fixed??

**Comment by Arumugaswami** [comment]
This is a little confusing to us, maybe because we entered in the wrong field, but we see that you are using verse level data to be applied to the scripture level data. May be fine, but confusing to us, should talk about it.

**Comment by subhakanta1979** [comment]
"save and publish" is working fine, we have only major table (normalized table or a datamart) for this new admin panel . it's T_Verse. This has got verse level data, chapter level data and document level data. Please refer to the screenshot , i was able to save the data and retrieve it after refreshing. 

The only issue is Reviewer Comments is appearing for the Next Verses also and in next to next too, we are fixing it. The Label which says "View All Reviewer Comments" might be confusing so we will change it to "View All Comments for This Verse"
![image](https://user-images.githubusercontent.com/43493826/65266079-f4e36580-db2f-11e9-8e06-05daaf536c88.png)

**Comment by subhakanta1979** [comment]
Note how the delete functionality is handled now, Only the admins can delete the comments. The reviewers cannot delete their own comments and before deleting it asks for a confirmation.

**Comment by Arumugaswami** [comment]
With regard only to the verse part at the top of the interface. When an entry is made for one verse in any of the four fields, then saved and published, those entries appear for every verse in the chapter, not for the single verse they were entered for. 
<img width="854" alt="Screen Shot 2019-09-19 at 8 01 08 PM" src="https://user-images.githubusercontent.com/33885813/65303066-a1195200-db18-11e9-9fe3-80337947df13.png">
<img width="861" alt="Screen Shot 2019-09-19 at 8 01 01 PM" src="https://user-images.githubusercontent.com/33885813/65303067-a1195200-db18-11e9-8fd2-69d90cd11eda.png">

**Comment by subhakanta1979** [comment]
Added a New Field to the DB because reviewer notes field is already being used at the Verse Level.
![image](https://user-images.githubusercontent.com/43493826/66172037-12ecb200-e668-11e9-8eb3-37d4b11034ff.png)
Subh Says It’s working Now. It’s Fixed
